services:
  app:
    container_name: "php-payment-system"
    build:
      context: .
      dockerfile: infra/Dockerfile
    working_dir: /app
    volumes:
      - ./:/app
    networks:
      - networks-payment-system
    ports:
      - 80:80
    depends_on:
      - database

  database:
    container_name: "db-payment-system"
    image: mariadb:latest
    restart: always
    environment:
      MARIADB_DATABASE: paymentsystem
      MARIADB_USER: devuser
      MARIADB_PASSWORD: devpass
      MARIADB_ROOT_PASSWORD: databaseroot
    volumes:
      - "./infra/mysql:/var/lib/mysql:Z"
    ports:
      - 3306:3306
    networks:
      - networks-payment-system

networks:
  networks-payment-system:
    driver: bridge
